### PR TITLE
Include sstream for std::stringstream

### PR DESCRIPTION
**Pull request by lwhsu**
Build with clang version 14.0.5:

```
src/McBopomofo.cpp:161:23: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
    std::stringstream sst;
                      ^
/usr/include/c++/v1/iosfwd:145:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
src/McBopomofo.cpp:179:23: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
    std::stringstream sst;
                      ^
/usr/include/c++/v1/iosfwd:145:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
2 errors generated.
```

### CODE REVIEW

**Comment by lukhnos** [comment]
Thanks!
